// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package server

import (
	"Week04/internal/app/demo-interface/service"
	"Week04/internal/pkg/dao"
	"Week04/internal/pkg/server"
	"database/sql"
)

// Injectors from wire.go:

func NewServerWire(listen string, db *sql.DB) server.IServer {
	iAccount := dao.NewAccount(db)
	iService := service.NewService(iAccount)
	router := NewRouter(iService)
	v := NewOptions()
	iServer := server.NewHttpServer(listen, router, v...)
	return iServer
}
